# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rubocop-extension-generator` gem.
# Please instead update this file by running `bin/tapioca gem rubocop-extension-generator`.


# source://rubocop-extension-generator//lib/rubocop/extension/generator/version.rb#3
module RuboCop; end

# source://rubocop-extension-generator//lib/rubocop/extension/generator/version.rb#4
module RuboCop::Extension; end

# source://rubocop-extension-generator//lib/rubocop/extension/generator/version.rb#5
module RuboCop::Extension::Generator; end

# source://rubocop-extension-generator//lib/rubocop/extension/generator/cli.rb#6
class RuboCop::Extension::Generator::CLI
  # @return [CLI] a new instance of CLI
  #
  # source://rubocop-extension-generator//lib/rubocop/extension/generator/cli.rb#17
  def initialize(argv); end

  # source://rubocop-extension-generator//lib/rubocop/extension/generator/cli.rb#21
  def run; end

  private

  # source://rubocop-extension-generator//lib/rubocop/extension/generator/cli.rb#34
  def fail!(opt); end

  class << self
    # source://rubocop-extension-generator//lib/rubocop/extension/generator/cli.rb#13
    def run(argv); end
  end
end

# source://rubocop-extension-generator//lib/rubocop/extension/generator/cli.rb#7
RuboCop::Extension::Generator::CLI::BANNER = T.let(T.unsafe(nil), String)

# source://rubocop-extension-generator//lib/rubocop/extension/generator/generator.rb#6
class RuboCop::Extension::Generator::Generator
  # @return [Generator] a new instance of Generator
  #
  # source://rubocop-extension-generator//lib/rubocop/extension/generator/generator.rb#7
  def initialize(name); end

  # source://rubocop-extension-generator//lib/rubocop/extension/generator/generator.rb#11
  def generate; end

  private

  # source://rubocop-extension-generator//lib/rubocop/extension/generator/generator.rb#199
  def classname; end

  # source://rubocop-extension-generator//lib/rubocop/extension/generator/generator.rb#203
  def cops_file_name; end

  # source://rubocop-extension-generator//lib/rubocop/extension/generator/generator.rb#185
  def delete(path); end

  # source://rubocop-extension-generator//lib/rubocop/extension/generator/generator.rb#195
  def dirname; end

  # Returns the value of attribute name.
  #
  # source://rubocop-extension-generator//lib/rubocop/extension/generator/generator.rb#207
  def name; end

  # source://rubocop-extension-generator//lib/rubocop/extension/generator/generator.rb#176
  def patch(path, pattern, replacement); end

  # source://rubocop-extension-generator//lib/rubocop/extension/generator/generator.rb#169
  def put(path, content); end

  # source://rubocop-extension-generator//lib/rubocop/extension/generator/generator.rb#191
  def root_path; end
end

# source://rubocop-extension-generator//lib/rubocop/extension/generator/version.rb#6
RuboCop::Extension::Generator::VERSION = T.let(T.unsafe(nil), String)
