Packs/ClassMethodsAsPublicApis:
  Enabled: false
  AcceptableParentClasses:
    - T::Enum
    - T::Struct
    - Struct
    - OpenStruct
  FailureMode: default

Packs/RootNamespaceIsPackName:
  Enabled: false
  FailureMode: default

Packs/TypedPublicApis:
  Enabled: false
  FailureMode: default

Packs/DocumentedPublicApis:
  Enabled: false
  FailureMode: default

PackwerkLite/Privacy:
  # It is recommended to use packwerk
  Enabled: false

PackwerkLite/Dependency:
  # It is recommended to use packwerk
  Enabled: false

# We do this inherit *after* setting the defaults so that pack-specific rubocops can override the defaults
inherit_from: ./pack_config.yml
