Packs/ClassMethodsAsPublicApis:
  Enabled: false
  AcceptableParentClasses:
    - T::Enum
    - T::Struct
    - Struct
    - OpenStruct
  AcceptableMixins: []
  FailureMode: default

Packs/RootNamespaceIsPackName:
  Enabled: false
  FailureMode: default

Packs/TypedPublicApis:
  Enabled: false
  FailureMode: default

Packs/DocumentedPublicApis:
  Enabled: false
  FailureMode: default

PackwerkLite/Privacy:
  # It is recommended to use packwerk
  Enabled: false

PackwerkLite/Dependency:
  # It is recommended to use packwerk
  Enabled: false

# We do this inherit *after* setting the defaults so that pack-specific rubocops can override the defaults
# Relevant documentation:
#  - Inheriting config from a gem:
#    - https://docs.rubocop.org/rubocop/configuration.html#inheriting-configuration-from-a-dependency-gem
#  - ERB in a .rubocop.yml file
#    - https://docs.rubocop.org/rubocop/configuration.html#pre-processing
<%= RuboCop::Packs.pack_based_rubocop_config %>
