Modularization/ClassMethodsAsPublicApis:
  Enabled: true
  AcceptableParentClasses:
    - T::Enum
    - T::Struct
    - Struct
    - OpenStruct

Modularization/NamespacedUnderPackageName:
  Enabled: false

Modularization/TypedPublicApi:
  Enabled: false

RequireDocumentedPublicApis:
  Enabled: false
