inherit_from: ./pack_config.yml

Packs/ClassMethodsAsPublicApis:
  Enabled: true
  AcceptableParentClasses:
    - T::Enum
    - T::Struct
    - Struct
    - OpenStruct

Packs/NamespaceConvention:
  Enabled: true

Packs/TypedPublicApi:
  Enabled: true

Packs/RequireDocumentedPublicApis:
  Enabled: true
