Packs/ClassMethodsAsPublicApis:
  Enabled: true
  AcceptableParentClasses:
    - T::Enum
    - T::Struct
    - Struct
    - OpenStruct

Packs/NamespacedUnderPackageName:
  Enabled: false

Packs/TypedPublicApi:
  Enabled: false

Packs/RequireDocumentedPublicApis:
  Enabled: false
