Packs/ClassMethodsAsPublicApis:
  Enabled: false
  AcceptableParentClasses:
    - T::Enum
    - T::Struct
    - Struct
    - OpenStruct
  AcceptableMixins: []
  FailureMode: default

Packs/RootNamespaceIsPackName:
  Enabled: false
  FailureMode: default

Packs/TypedPublicApis:
  Enabled: false
  FailureMode: default

Packs/DocumentedPublicApis:
  Enabled: false
  FailureMode: default

PackwerkLite/Privacy:
  # It is recommended to use packwerk
  Enabled: false

PackwerkLite/Dependency:
  # It is recommended to use packwerk
  Enabled: false
