inherit_from: ./pack_config.yml

Packs/ClassMethodsAsPublicApis:
  Enabled: true
  AcceptableParentClasses:
    - T::Enum
    - T::Struct
    - Struct
    - OpenStruct
  FailureMode: default

Packs/RootNamespaceIsPackName:
  Enabled: true
  FailureMode: default

Packs/TypedPublicApis:
  Enabled: true
  FailureMode: default

Packs/DocumentedPublicApis:
  Enabled: true
  FailureMode: default

PackwerkLite/Privacy:
  # It is recommended to use packwerk
  Enabled: false

PackwerkLite/Dependency:
  # It is recommended to use packwerk
  Enabled: false
