Packs/ClassMethodsAsPublicApis:
  Enabled: false
  AcceptableParentClasses:
    - T::Enum
    - T::Struct
    - Struct
    - OpenStruct
  AcceptableMixins: []

Packs/RootNamespaceIsPackName:
  Enabled: false

Packs/TypedPublicApis:
  Enabled: false

Packs/DocumentedPublicApis:
  Enabled: false

PackwerkLite/Privacy:
  # It is recommended to use packwerk
  Enabled: false

PackwerkLite/Dependency:
  # It is recommended to use packwerk
  Enabled: false
