# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::RSpec; end
module RuboCop::Modularization::Inject::Config; end
module RuboCop::Modularization::Inject::ConfigLoader; end
module RuboCop::RSpec::ExpectOffense; end
